# pyproject.tomlのビルドツールを指定します。
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# プロジェクトの設定を書きます。
[project]
name = "project"
version = "0.0.1"
description = "pyproject.tomlのテスト"
requires-python = ">=3.11"
