name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.13.2

      - name: change directory into project
        run: cd project

      - name: Run tests
        run: python -m unittest -v tests.test_sample
