name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.13.2

      - name: unittest step
        run: |
          ls ~/
          pwd
          cd ./project/tests/
          pwd
          ls -a
          python -m unittest -v test_main
